### ISSUE TITLE
Your website is not working

### ISSUE THREAD

**Issue by MoSattler** [Drop-OSS/drop#10]
<img width="1190" alt="Screenshot 2024-12-04 at 11 59 53" src="https://github.com/user-attachments/assets/0631977c-196e-4c2b-90a2-933142229db9">

**Comment by DecDuck** [comment]
It's always DNS.

It's fixed now, thankfully.

**Comment by MoSattler** [comment]
The problem remains for me 

![IMG_6872](https://github.com/user-attachments/assets/63d40c5c-69b8-4f91-a813-27054f20eee4)

**Comment by DecDuck** [comment]
Thank you - the Kubernetes cluster is having issues, so the website will be down until it's fixed.

If you're looking for information about Drop, the website doesn't have any information. If you want to check it out, I'd suggest joining the Discord server to setting up your own server.
